repos:
  # Black
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11
  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format