[tool.black]
target-version = ['py311']
line-length = 99

[tool.ruff]
target-version = "py311"
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = ["B023", "B905", "COM812", "CPY", "D", "FBT", "FURB", "G004", "ISC001", "N812", "PLW2901", "S101", "T20"]