[tool.black]
target-version = ['py311']
line-length = 99

[tool.isort]
py_version = 311
line_length = 99
skip_gitignore = true

[tool.ruff]
target-version = "py311"
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = ["B023", "B905", "CPY", "D", "FBT", "FURB", "G004", "N812", "PLW2901", "T20"]